openapi: 3.1.0
info:
  title: TB Case Management System API
  description: Backend REST API for maintaining entries on the Defra AI Tech Radar - TB Case Management System
  version: 1.0.0

servers:
  - url: /api/v1
    description: Version 1 API

tags:
  - name: reference
    description: Reference data operations
  - name: tb-status
    description: TB status reference data
  - name: tb-result
    description: TB result reference data
  - name: allocation-booking-method
    description: Allocation booking method reference data
  - name: allocation-skip-reason
    description: Allocation skip reason reference data
  - name: finishing-unit
    description: Finishing unit reference data
  - name: holding
    description: Holding management operations

paths:
  /reference/tb-status:
    get:
      tags:
        - reference
        - tb-status
      summary: Get all TB status options
      description: Retrieve all TB status options with optional region filtering
      operationId: getTbStatus
      parameters:
        - name: region
          in: query
          description: Optional region filter to get TB statuses specific to a region
          required: false
          schema:
            type: string
            example: "Midlands"
      responses:
        '200':
          description: Successful response with TB status data
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/TbStatusOption'
              example:
                data:
                  - code: "TB1"
                    description: "Officially TB Free"
                    regions: ["Midlands", "South West"]
                  - code: "TB2"
                    description: "TB Restricted"
                    regions: ["Midlands"]

  /reference/tb-result:
    get:
      tags:
        - reference
        - tb-result
      summary: Get all TB result options
      description: Retrieve all TB result options for lookup purposes
      operationId: getTbResult
      responses:
        '200':
          description: Successful response with TB result data
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/TbResultOption'
              example:
                data:
                  - code: "NVL"
                    description: "NVL"
                  - code: "NVL - Neg"
                    description: "NVL - Neg"
                  - code: "VL - Pos"
                    description: "VL - Pos"

  /reference/allocation-booking-method:
    get:
      tags:
        - reference
        - allocation-booking-method
      summary: Get all allocation booking method options
      description: Retrieve all allocation booking method options for lookup purposes
      operationId: getAllocationBookingMethod
      responses:
        '200':
          description: Successful response with allocation booking method data
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/AllocationBookingMethodOption'
              example:
                data:
                  - method: "Phone"
                  - method: "Email"
                  - method: "Online Portal"

  /reference/allocation-skip-reason:
    get:
      tags:
        - reference
        - allocation-skip-reason
      summary: Get all allocation skip reason options
      description: Retrieve all allocation skip reason options for lookup purposes
      operationId: getAllocationSkipReasons
      responses:
        '200':
          description: Successful response with allocation skip reason data
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/AllocationSkipReasonOption'
              example:
                data:
                  - reason: "Declined"
                  - reason: "Not Necessary"
                  - reason: "N/A High Risk"

  /reference/finishing-unit:
    get:
      tags:
        - reference
        - finishing-unit
      summary: Get all finishing unit options
      description: Retrieve all finishing unit options with optional region filtering
      operationId: getFinishingUnits
      parameters:
        - name: region
          in: query
          description: Optional region filter to get finishing units specific to a region
          required: false
          schema:
            type: string
            example: "midlands"
      responses:
        '200':
          description: Successful response with finishing unit data
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/FinishingUnitOption'
              example:
                data:
                  - unitType: "Grazing AFU"
                    regions: ["midlands", "north", "south_east", "south_west"]
                  - unitType: "Non-Grazing AFU"
                    regions: ["midlands", "north", "south_east", "south_west", "wales"]

  /holding:
    post:
      tags:
        - holding
      summary: Create a new holding
      description: Create a new holding with address, geolocation, and contact information
      operationId: createHolding
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateHoldingRequest'
            example:
              details:
                cph: "12345678901"
                name: "Green Acres Farm"
                description: "Dairy farm in the countryside"
                address:
                  street: "123 Farm Lane"
                  locality: "Little Village"
                  town: "Markettown"
                  county: "Middlesex"
                  postcode: "AB12 3CD"
                geolocation:
                  mapReference: "TQ123456"
                  easting: 512345
                  northing: 187654
                contacts:
                  - type: "landline"
                    value: "01234 567890"
                  - type: "mobile"
                    value: "07700 123456"
      responses:
        '201':
          description: Holding created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/HoldingResponse'
        '400':
          description: Invalid request data
        '409':
          description: Holding with this CPH already exists
        '500':
          description: Internal server error
    get:
      tags:
        - holding
      summary: Get all holdings
      description: Retrieve a summary list of all holdings
      operationId: getAllHoldings
      responses:
        '200':
          description: Successful response with holdings data
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/HoldingSummary'
        '500':
          description: Internal server error

  /holding/{id}:
    get:
      tags:
        - holding
      summary: Get holding by ID
      description: Retrieve a specific holding by its MongoDB ObjectId
      operationId: getHoldingById
      parameters:
        - name: id
          in: path
          required: true
          description: Holding ObjectId
          schema:
            type: string
            pattern: '^[0-9a-fA-F]{24}$'
            example: "507f1f77bcf86cd799439011"
      responses:
        '200':
          description: Successful response with holding data
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/HoldingResponse'
        '404':
          description: Holding not found
        '500':
          description: Internal server error

components:
  schemas:
    TbStatusOption:
      type: object
      description: A TB status option with associated regions
      properties:
        code:
          type: string
          description: TB status code
          example: "TB1"
        description:
          type: string
          description: TB status description
          example: "Officially TB Free"
        regions:
          type: array
          description: List of regions where this status is valid
          items:
            type: string
          example: ["Midlands", "South West"]
      required:
        - code
        - description
        - regions

    TbResultOption:
      type: object
      description: A TB result option for lookup purposes
      properties:
        code:
          type: string
          description: TB result code
          example: "NVL"
        description:
          type: string
          description: TB result description
          example: "NVL"
      required:
        - code
        - description

    AllocationBookingMethodOption:
      type: object
      description: An allocation booking method option for lookup purposes
      properties:
        method:
          type: string
          description: Allocation booking method
          example: "Phone"
      required:
        - method

    AllocationSkipReasonOption:
      type: object
      description: An allocation skip reason option for lookup purposes
      properties:
        reason:
          type: string
          description: Allocation skip reason
          example: "Declined"
      required:
        - reason

    FinishingUnitOption:
      type: object
      description: A finishing unit option with associated regions
      properties:
        unitType:
          type: string
          description: Finishing unit type
          example: "Grazing AFU"
        regions:
          type: array
          description: List of regions where this finishing unit type is valid
          items:
            type: string
          example: ["midlands", "north", "south_east", "south_west"]
      required:
        - unitType
        - regions

    Address:
      type: object
      description: Address information for a holding
      properties:
        street:
          type: string
          description: Street address
          example: "123 Farm Lane"
        locality:
          type: string
          description: Locality
          example: "Little Village"
        town:
          type: string
          description: Town name
          example: "Markettown"
        county:
          type: string
          description: County name
          example: "Middlesex"
        postcode:
          type: string
          description: UK postcode
          pattern: '^[A-Z]{1,2}[0-9R][0-9A-Z]? [0-9][A-Z-[CIKMOV]]{2}$'
          example: "AB12 3CD"
      required:
        - town
        - county
        - postcode

    Contact:
      type: object
      description: Contact information
      properties:
        type:
          type: string
          enum: ["landline", "mobile"]
          description: Contact type
          example: "landline"
        value:
          type: string
          description: Contact number
          pattern: '^[0-9\s\-\+\(\)]+$'
          example: "01234 567890"
      required:
        - type
        - value

    Geolocation:
      type: object
      description: Geographic coordinates
      properties:
        mapReference:
          type: string
          description: Map reference
          example: "TQ123456"
        easting:
          type: integer
          minimum: 0
          maximum: 999999
          description: Easting coordinate
          example: 512345
        northing:
          type: integer
          minimum: 0
          maximum: 999999
          description: Northing coordinate
          example: 187654

    HoldingDetails:
      type: object
      description: Detailed information about a holding
      properties:
        cph:
          type: string
          description: County Parish Holding identifier (11 digits)
          pattern: '^[0-9]{11}$'
          example: "12345678901"
        name:
          type: string
          description: Holding name
          minLength: 1
          maxLength: 255
          example: "Green Acres Farm"
        description:
          type: string
          description: Holding description
          maxLength: 1000
          example: "Dairy farm in the countryside"
        address:
          $ref: '#/components/schemas/Address'
        geolocation:
          $ref: '#/components/schemas/Geolocation'
        contacts:
          type: array
          description: Contact information
          items:
            $ref: '#/components/schemas/Contact'
          default: []
      required:
        - cph
        - name
        - address

    CreateHoldingRequest:
      type: object
      description: Request body for creating a new holding
      properties:
        details:
          $ref: '#/components/schemas/HoldingDetails'
      required:
        - details

    HoldingResponse:
      type: object
      description: Complete holding information
      properties:
        id:
          type: string
          description: Holding ObjectId
          pattern: '^[0-9a-fA-F]{24}$'
          example: "507f1f77bcf86cd799439011"
        details:
          $ref: '#/components/schemas/HoldingDetails'
        incidents:
          type: array
          description: Array of incident IDs
          items:
            type: string
            pattern: '^[0-9a-fA-F]{24}$'
          example: []
      required:
        - id
        - details

    HoldingSummary:
      type: object
      description: Summary information for holding list displays
      properties:
        id:
          type: string
          description: Holding ObjectId
          pattern: '^[0-9a-fA-F]{24}$'
          example: "507f1f77bcf86cd799439011"
        cph:
          type: string
          description: County Parish Holding identifier
          example: "12345678901"
        name:
          type: string
          description: Holding name
          example: "Green Acres Farm"
        description:
          type: string
          description: Holding description
          example: "Dairy farm in the countryside"
        address:
          type: object
          description: Simplified address information
          properties:
            town:
              type: string
              example: "Markettown"
            county:
              type: string
              example: "Middlesex"
            postcode:
              type: string
              example: "AB12 3CD"
        incidentCount:
          type: integer
          description: Number of associated incidents
          example: 0
      required:
        - id
